export default [
  { code: 610, name: 'Corredores' },
  { code: 607, name: 'Golfito' },
  { code: 608, name: 'Coto Brus' },
  { code: 605, name: 'Osa' },
  { code: 603, name: 'Buenos Aires' },
  { code: 119, name: 'Pérez Zeledón' },
  { code: 606, name: 'Quepos' },
  { code: 704, name: 'Talamanca' },
  { code: 609, name: 'Parrita' },
  { code: 105, name: 'Tarrazú' },
  { code: 117, name: 'Dota' },
  { code: 611, name: 'Garabito' },
  { code: 120, name: 'León Cortés Castro' },
  { code: 104, name: 'Puriscal' },
  { code: 106, name: 'Aserrí' },
  { code: 103, name: 'Desamparados' },
  { code: 112, name: 'Acosta' },
  { code: 116, name: 'Turrubares' },
  { code: 308, name: 'El Guarco' },
  { code: 301, name: 'Cartago' },
  { code: 601, name: 'Puntarenas' },
  { code: 302, name: 'Paraíso' },
  { code: 304, name: 'Jiménez' },
  { code: 305, name: 'Turrialba' },
  { code: 107, name: 'Mora' },
  { code: 307, name: 'Oreamuno' },
  { code: 110, name: 'Alajuelita' },
  { code: 701, name: 'Limón' },
  { code: 303, name: 'La Unión' },
  { code: 118, name: 'Curridabat' },
  { code: 209, name: 'Orotina' },
  { code: 101, name: 'San José' },
  { code: 102, name: 'Escazú' },
  { code: 306, name: 'Alvarado' },
  { code: 109, name: 'Santa Ana' },
  { code: 509, name: 'Nandayure' },
  { code: 115, name: 'Montes de Oca' },
  { code: 108, name: 'Goicoechea' },
  { code: 113, name: 'Tibás' },
  { code: 204, name: 'San Mateo' },
  { code: 502, name: 'Nicoya' },
  { code: 205, name: 'Atenas' },
  { code: 201, name: 'Alajuela' },
  { code: 114, name: 'Moravia' },
  { code: 602, name: 'Esparza' },
  { code: 111, name: 'Vázquez de Coronado' },
  { code: 403, name: 'Santo Domingo' },
  { code: 407, name: 'Belén' },
  { code: 409, name: 'San Pablo' },
  { code: 202, name: 'San Ramón' },
  { code: 401, name: 'Heredia' },
  { code: 511, name: 'Hojancha' },
  { code: 408, name: 'Flores' },
  { code: 405, name: 'San Rafael' },
  { code: 402, name: 'Barva' },
  { code: 406, name: 'San Isidro' },
  { code: 404, name: 'Santa Barbara' },
  { code: 207, name: 'Palmares' },
  { code: 208, name: 'Poás' },
  { code: 203, name: 'Grecia' },
  { code: 206, name: 'Naranjo' },
  { code: 604, name: 'Montes de Oro' },
  { code: 212, name: 'Sarchí' },
  { code: 703, name: 'Siquirres' },
  { code: 705, name: 'Matina' },
  { code: 503, name: 'Santa Cruz' },
  { code: 211, name: 'Zarcero' },
  { code: 706, name: 'Guácimo' },
  { code: 507, name: 'Abangares' },
  { code: 702, name: 'Pococí' },
  { code: 210, name: 'San Carlos' },
  { code: 506, name: 'Cañas' },
  { code: 508, name: 'Tilarán' },
  { code: 410, name: 'Sarapiquí' },
  { code: 505, name: 'Carrillo' },
  { code: 216, name: 'Río Cuarto' },
  { code: 504, name: 'Bagaces' },
  { code: 215, name: 'Guatuso' },
  { code: 214, name: 'Los Chiles' },
  { code: 501, name: 'Liberia' },
  { code: 213, name: 'Upala' },
  { code: 510, name: 'La Cruz' }
]
